# Site settings
title: Abdul Hafeez
subtitle: "Computer Scientist"
email: engrhafeez@gmail.com
description: "Accelerate collaboration between materials, manufacturing, and data scientists"
baseurl: "travelog-theme"
url: "ahafeez7.github.io"
twitter_username: "hokie khan"
github_username:  "ahafeez7"
instagram_username: "rowanoulton"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed
